version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:v1.13.0
    container_name: qdrant
    ports:
      - "6333:6333" # HTTP API port
      - "6334:6334" # gRPC API port
    volumes:
      - ./qdrant_storage:/qdrant/storage # Persistent storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__STORAGE__PATH: /qdrant/storage
    restart: always
    networks:
      - qdrant_network

networks:
  qdrant_network:
    driver: bridge
